---
title: "Tidy Tuesday Super Bowl Ads"
author: "Jeff Grayum"
date: "3/8/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries and packages
```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggthemes)
library(lubridate)
```

Loading dataset
```{r}
tuesdata <- tidytuesdayR::tt_load('2021-03-02')

youtube <- tuesdata$youtube %>%
  select(-favorite_count)

youtube %>%
  view()
```

Getting a feel for the dataset.
```{r}
youtube %>%
  count(brand, sort = TRUE) %>%
  head(10) %>%
  mutate(brand = fct_reorder(brand, n)) %>%
  ggplot(aes(n, brand, fill = brand)) +
  geom_col() +
  labs(title = "Biggest Super Bowl sponsors",
       x = "Number of ads",
       y = "Brand",
       caption = "Source: FiveThirtyEight") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        legend.position = "none")
```

```{r}
youtube %>%
  ggplot(aes(year, fill = brand)) +
  geom_bar() +
  facet_wrap(~ brand) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        legend.position = "none") +
  labs(title = "Biggest sponsors each year of the Super Bowl",
       x = "Year",
       y = "Number of ads",
       caption = "Source: FiveThirtyEight")
```


```{r}
youtube %>%
  gather(metric, value, contains("_count")) %>%
  ggplot(aes(value)) +
  geom_histogram(aes(fill = metric), bindiwdth = 0.5) +
  scale_x_log10(labels = comma) +
  theme_fivethirtyeight() +
  labs(x = "Number of Views",
       y = "Count",
       title = "Distribution of YouTube Super Bowl ad metrics") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        legend.position = "none") +
  facet_wrap(~ metric) 
```

```{r}

#Below, fct_reorder would not work until we filtered NA's! Consider this if ungrouping isnt fixing this issue.
youtube %>%
  filter(!is.na(view_count)) %>%
  mutate(brand = fct_reorder(brand, view_count)) %>%
  ggplot(aes(view_count, brand)) +
  geom_boxplot() + 
  scale_x_log10(labels = comma) +
  labs(x = "Number of views",
       y = "Brand",
       title = "Most viewed Super Bowl YouTube ads") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

youtube %>%
  ggplot(aes(year, view_count, group = year)) +
  geom_boxplot() + 
  scale_y_log10(labels = comma) +
  labs(x = "Year",
       y = "Number of views",
       title = "Number of Super Bowl ads viewed each year") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

#Let's look at median views per year, using group_by and summarize
youtube %>%
  filter(!is.na(view_count)) %>%
  group_by(year) %>%
  summarize(n = n(),
            median_views = median(view_count)) %>%
  filter(n >= 7) %>%
  ggplot(aes(year, median_views)) +
  geom_line() +
  geom_point(aes(size = n)) +
  theme_fivethirtyeight() +
  labs(x = "Year",
       y = "Median number of views",
       title = "Median number of views of YouTube Super Bowl ads per year") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        legend.position = "none") +
  scale_y_continuous(labels = comma)
```


```{r}
youtube %>%
  filter(year == "2017") %>%
  arrange(desc(view_count)) %>%
  view()
```

Let's look at the qualifications (e.g. "funny", "sexual", etc)
```{r}
#Gather: first var is title to gather variables under, second is title to gather values under, third is what to gather.  This is not an amazing way to look at this.
youtube %>%
  gather(category, value, funny:use_sex) %>%
  ggplot(aes(category, view_count, fill = value)) + 
  geom_boxplot() +
  scale_y_log10(labels = comma) +
  theme_fivethirtyeight() +
  labs(title = "What has the greatest influence on the viewcount of YouTube Super Bowl ads",
       x = "Category",
       y = "View count",
       fill = "") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

#Let's try a different approach
youtube %>%
  filter(!is.na(view_count)) %>%
  gather(category, value, funny:use_sex) %>%
  group_by(category, value) %>%
  summarize(n = n(),
            median_view_count = median(view_count)) %>%
  ggplot(aes(category, median_view_count, fill = value)) +
  geom_col(position = "dodge") +
  theme_fivethirtyeight() +
  labs(title = "What has the greatest influence on the viewcount of YouTube Super Bowl ads",
       x = "Category",
       y = "Median view count",
       fill = "") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))
#position = "dodge" places bars in same category beside each other, rather than stacking them!
#This graph supports that patriotism and danger increase view counts!

#Below, a great example of how to use cor() to analyze correlations between variables and values!!
youtube %>%
  filter(!is.na(view_count)) %>%
  gather(category, value, funny:use_sex) %>%
  group_by(category) %>%
  summarize(correleation = cor(value, log(view_count + 1))) %>%
  arrange(desc(correleation))

#LETS MAKE A LINEAR MODEL BROTHER 
lm(log2(view_count) ~ danger + patriotic + funny + 
     show_product_quickly + celebrity + animals + use_sex,
   data = youtube) %>%
  summary()
```

